/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Opt(IDL.Int),
});
export const PDF = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'fileData' : IDL.Vec(IDL.Nat8),
  'description' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'questionContent' : IDL.Text,
});
export const Syllabus = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'subject' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'courseDetails' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
  'createPDF' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [PDF],
      [],
    ),
  'createQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [Question],
      [],
    ),
  'createSyllabus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Syllabus],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deletePDF' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteSyllabus' : IDL.Func([IDL.Nat], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllPDFs' : IDL.Func([], [IDL.Vec(PDF)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllSyllabuses' : IDL.Func([], [IDL.Vec(Syllabus)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
  'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(PDF)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getSyllabus' : IDL.Func([IDL.Nat], [IDL.Opt(Syllabus)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNote' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [Note], []),
  'updatePDF' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PDF], []),
  'updateQuestion' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [Question],
      [],
    ),
  'updateSyllabus' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [Syllabus],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Opt(IDL.Int),
  });
  const PDF = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'fileData' : IDL.Vec(IDL.Nat8),
    'description' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'questionContent' : IDL.Text,
  });
  const Syllabus = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'subject' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'courseDetails' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Note], []),
    'createPDF' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [PDF],
        [],
      ),
    'createQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [Question],
        [],
      ),
    'createSyllabus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Syllabus],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deletePDF' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteSyllabus' : IDL.Func([IDL.Nat], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllPDFs' : IDL.Func([], [IDL.Vec(PDF)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllSyllabuses' : IDL.Func([], [IDL.Vec(Syllabus)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Nat], [IDL.Opt(Note)], ['query']),
    'getPDF' : IDL.Func([IDL.Nat], [IDL.Opt(PDF)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getSyllabus' : IDL.Func([IDL.Nat], [IDL.Opt(Syllabus)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Note],
        [],
      ),
    'updatePDF' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PDF], []),
    'updateQuestion' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [Question],
        [],
      ),
    'updateSyllabus' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [Syllabus],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };